version: 2
jobs:
  test:
    docker:
      - image: nrel/openstudio:2.8.1
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Update all measures
          command: |
            rake update_measures
      - run: 
          name: Regenerate test osms
          command: |
            rake test:regenerate_osms
      - run: 
          name: Run all unit tests
          command: |
            rake test:unit_tests
      - run:
          name: Run all regression tests
          command: |
            rake test:regression_tests
      - store_artifacts:
            path: workflows/results
            destination: results
  progress:
    docker:
      - image: nrel/openstudio:2.8.1
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: P v M
          command: |
            rake progress:example
workflows:
  version: 2
  commit:
    jobs:
      - test
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - workflow-schedule
    jobs:
      - progress
