version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.9.0
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Apply rubocop
          command: |
            rubocop --format simple --only Layout --debug
      - run:
          name: Update all measures
          command: |
            rake update_measures
      - run: 
          name: Regenerate test osms
          command: |
            rake test:regenerate_osms
      - run: 
          name: Run all unit tests
          command: |
            rake test:unit_tests
      - run:
          name: Run all regression tests
          command: |
            rake test:regression_tests
      - store_artifacts:
            path: workflows/results
            destination: results
