version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.8.0
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run: 
          name: Regenerate test osm files
          command: |
            rake test:regenerate_osms
      - run: 
          name: Run tests
          command: |
            rake test:all
      - store_artifacts:
            path: workflows/results
            destination: results
