version: 2
jobs:
  test:
    docker:
      - image: nrel/openstudio:2.8.1
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Update all measures
          command: |
            rake update_measures
      - run: 
          name: Regenerate test osms
          command: |
            rake test:regenerate_osms
      - run: 
          name: Run all unit tests
          command: |
            rake test:unit_tests
      - run:
          name: Run all regression tests
          command: |
            rake test:regression_tests
      - store_artifacts:
            path: workflows/results
            destination: workflows
  progress:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install env
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install pandas
            pip install awscli
      - run:
          name: Retrieve results
          command: |
            source env/bin/activate
            aws configure list
            DATESTRING="$(date '+%Y-%m-%d')"
            echo "export DATESTRING=$DATESTRING" >> $BASH_ENV
            QUERYID=`aws athena start-query-execution --query-string "select * from run3_baseline" --query-execution-context Database=idsm-scout --result-configuration OutputLocation=s3://resbldg-datasets/resstock-progress/$DATESTRING --output text`
            aws athena get-query-execution --query-execution-id "${QUERYID}"
            sleep 60
            aws s3 cp s3://resbldg-datasets/resstock-progress/$DATESTRING/$QUERYID.csv ./
      - run:
          name: P v M
          command: |
            source env/bin/activate
            python scripts/progress.py
            aws s3 sync ./progress/ s3://resbldg-datasets/resstock-progress/$DATESTRING/
      - store_artifacts:
            path: progress
            destination: progress
workflows:
  version: 2
  commit:
    jobs:
      - test
  # weekly:
    # triggers:
      # - schedule:
          # cron: "0 0 * * 0"
          # filters:
            # branches:
              # only:
                # - workflow-schedule
    # jobs:
      # - progress
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - workflow-schedule
    jobs:
      - progress